name: withhelpofparameters
on:
  workflow_dispatch:
    inputs:
      typeofenv:
        default: "test"
        description: "Project Environment"
        required: true
        type: choice
        options:
          - test
          - dev
          - preprod
          - uat
          - xyz
jobs:
    myjob:
      runs-on: self-hosted
      steps:
        - name: displyvariablename
          run: echo "Value of env is ${{ inputs.typeofenv }}"
