
name: workflow1
on:
  push:
    branches:
      - main

jobs:
    displaymessage1:
        runs-on: self-hosted
        steps:
           - name: Display Message on the screen
             run: echo "Good Morning"
    displaymessage2:
        needs: displaymessage1
        runs-on: self-hosted
        steps:
           - name: Display Message on the screen
             run: echo "Good Morning"
    displaymessage3:
        runs-on: self-hosted
        needs: [displaymessage1,displaymessage2]

        steps:
           - name: Display Message on the screen
             run: echo "Good Morning"                          

